Added options to control build.

diff --git a/shell/local/arcordia/functions/updatebuild b/shell/local/arcordia/functions/updatebuild
--- a/shell/local/arcordia/functions/updatebuild
+++ b/shell/local/arcordia/functions/updatebuild
@@ -1,8 +1,10 @@
 # ZSH function file
 # Update configspec to current time & rebuild the cashsec system
-# Usage: updatebuild [clean]
+# Usage: updatebuild [-c] [-n]
+#	 -c	Build from clean
+#	 -n	Don't build. Just update configspec
 #
-# $Id: updatebuild,v 1.1 2001/02/21 11:22:23 mebourne Exp $
+# $Id: updatebuild,v 1.2 2001/02/21 12:06:38 mebourne Exp $
 
 local param=$1
 local file=${TMPPREFIX:-/tmp/zsh}.configspec.$$
@@ -11,6 +13,17 @@ local time=$(date '+%d-%b.%H:%M')
 cleartool catcs |
   sed "s/[0-9][0-9]-[A-Z][a-z][a-z].[0-9][0-9]:[0-9][0-9]/$time/g" > $file &&
   cleartool setcs $file &&
-  rm -f $file &&
-  echo "Updated config spec to $time" &&
-  build $param
+  rm -f $file
+
+if (( $? == 0 ))
+then
+  echo "Updated config spec to $time"
+
+  case $param in
+    -c)	build clean && build;;
+    -n)	;;
+    "")	build;;
+    *)	echo "Invalid option $param" 1>&2
+        return 1;;
+  esac
+fi
