Added kerberos support to sql

diff --git a/shell/package/sql/base/functions/_sql_execute_dbi b/shell/package/sql/base/functions/_sql_execute_dbi
--- a/shell/package/sql/base/functions/_sql_execute_dbi
+++ b/shell/package/sql/base/functions/_sql_execute_dbi
@@ -5,10 +5,16 @@
 #
 # $Id$
 
-if [[ -z $_sql_parameters[user] ]]
+local kerberos=""
+if (( ${_sql_parameters[kerberos]:-0} ))
 then
-  echo "Error: SQL user variable not set" 1>&2
-  return 1
+  kerberos="--kerberos=$_sql_parameters[server]"
+else
+  if [[ -z $_sql_parameters[user] ]]
+  then
+    echo "Error: SQL user variable not set" 1>&2
+    return 1
+  fi
 fi
 
 # Check the auto-commit option
@@ -31,7 +37,7 @@ _sql_call dbi_params
 # Capitalise the vendor name and try it as the driver. Use server for connect string
 $_sql_dbiprogram --driver=$driver \
                  ${connect:+--connect=${(j:;:)connect}} \
-                 --user=$_sql_parameters[user] \
+                 $kerberos --user=$_sql_parameters[user] \
                  ${_sql_parameters[password]:+--password=$_sql_parameters[password]} \
                  $opts \
                  "$argv[@]"
diff --git a/shell/package/sql/sybase/functions/_sybase_rawsql b/shell/package/sql/sybase/functions/_sybase_rawsql
--- a/shell/package/sql/sybase/functions/_sybase_rawsql
+++ b/shell/package/sql/sybase/functions/_sybase_rawsql
@@ -3,16 +3,29 @@
 # Execute a raw SQL command
 # For use only by the SQL packages
 #
-# $Id: _sybase_rawsql 792 2003-09-22 11:47:18Z martin $
+# $Id$
 
-if [[ -z $_sql_parameters[server] || -z $_sql_parameters[user] || -z $_sql_parameters[password] ]]
+if [[ -z $_sql_parameters[server] ]]
 then
-  echo "Error: SQL server/user/password variables not set" 1>&2
+  echo "Error: SQL server variable not set" 1>&2
   return 1
 fi
 
-isql -S$_sql_parameters[server] \
-     -U$_sql_parameters[user] \
-     -P$_sql_parameters[password] \
-     ${_sql_parameters[database]:+-D$_sql_parameters[database]} \
-     "$argv[@]"
+if (( ${_sql_parameters[kerberos]:-0} ))
+then
+  kisql -S$_sql_parameters[server] -K \
+        ${_sql_parameters[database]:+-D$_sql_parameters[database]} \
+        "$argv[@]"
+else
+  if [[ -z $_sql_parameters[user] || -z $_sql_parameters[password] ]]
+  then
+    echo "Error: SQL user/password variables not set" 1>&2
+    return 1
+  fi
+
+  isql -S$_sql_parameters[server] \
+       -U$_sql_parameters[user] \
+       -P$_sql_parameters[password] \
+       ${_sql_parameters[database]:+-D$_sql_parameters[database]} \
+       "$argv[@]"
+fi
