Added special fullcommand type. Re-worked to use simulated nested associative arrays (using '.' separated key fields).

diff --git a/shell/system/functions/parse_opts b/shell/system/functions/parse_opts
--- a/shell/system/functions/parse_opts
+++ b/shell/system/functions/parse_opts
@@ -2,7 +2,7 @@
 # Provide options parsing and help output
 # Usage: parse_opts <argv> <results> [<help>]
 #
-# $Id: parse_opts,v 1.18 2001/08/10 17:01:58 mebourne Exp $
+# $Id: parse_opts,v 1.19 2001/08/16 15:29:06 mebourne Exp $
 
 ### Documentation
 
@@ -98,8 +98,14 @@ _parse_opts_setupdefinitions() {
 #type option        exec=_parse_opts_validate_option "zsh option"               _options
 #type parameter     values=${(k)parameters}          parameter                  _parameters
 
+## Complex type for sub commands - ie. where a real command is passed as an
+## argument. Note that this type may currently only be used for argument
+## specifications, and only with a frequency of [*], [1,*], etc
+#type fullcommand   string                           ""                         " _normal" \
+      * complete.restrict=match
+
 # --help
-# --zsh-completion
+# --zsh-completion * complete.hidden
 '
 }
 
@@ -122,9 +128,67 @@ _parse_opts_validate_option() {
 # calling program's name space
 
 
+# Print an associative array which multi-field keys ('.' delimited), as if it
+# were a real nested structure. Currently only handles one level of 'nesting'
+# though. Used for debugging
+_parse_opts_showdata() {
+  local var="$argv[1]"
+
+  # Make a copy of the array because otherwise we have trouble later
+  local -A data
+  data=("${(@Pkv)var}")
+
+  echo "$var = {"
+
+  # Collect the first field from the keys, uniqued
+  local -aU stems
+  stems=(${(k)data%%.*})
+
+  # Process each of the first fields
+  local -a keys
+  for stem in ${(o)stems}
+  do
+    echo "  $stem = {"
+
+    # Get a list of matching full keys
+    keys=(${${(Mk)data:#$stem.*}#$stem.})
+
+    # Work out the width of field padding required
+    integer length=0
+    local key=""
+    for key in $keys
+    do
+      if (( $#key > length ))
+      then
+  	length=$#key
+      fi
+    done
+
+    # Print each of the key/value pairs
+    local key=""
+    for key in ${(o)keys}
+    do
+      echo "    ${(r:length:::::)key} = '$data[$stem.$key]'"
+    done
+
+    echo "  }"
+  done
+
+  echo "}"
+}
+
 # This function handles the parsing of option definitions for
 # _parse_opts_parsehelp (uses locals directly)
 _parse_opts_parseoption() {
+
+  # Extract the special parameters if there are any
+  local -a parameters
+  if (( paraminfo[(I)\*] ))
+  then
+    parameters=($paraminfo[paraminfo[(I)\*]+1,-1])
+    paraminfo=($paraminfo[1,paraminfo[(I)\*]-1])
+  fi
+
   # Extract the type information if there is any
   local type=""
   if (( paraminfo[(I):] ))
@@ -177,6 +241,13 @@ _parse_opts_parseoption() {
   do
     local aliases="" excludes=""
 
+    # Check for invalid characters in option name
+    if [[ $option != [-_[:alnum:]]## ]]
+    then
+      echo "Invalid name for option/argument: '$option'" 1>&2
+      return 1
+    fi
+
     # Establish defaults for missing values
     if [[ $option == -* ]]
     then
@@ -206,35 +277,36 @@ _parse_opts_parseoption() {
       (( _po_minargs += min_frequency ))
     fi
 
-    # Report info on option if debugging enabled
-    if (( _po_debug ))
-    then
-      echo "option = '$option' {"
-      echo "  tag       = '$tag'"
-      echo "  frequency = '$frequency'"
-      echo "  type      = '$type'"
-      echo "  help      = '$helpline'"
-      echo "  excludes  = '$excludes'"
-      echo "  aliases   = '$aliases'"
-      echo "}"
-    fi
-
     # Store the main data for this option
-    _po_tags[$option]=$tag
-    _po_frequencies[$option]=$frequency
-    _po_types[$option]=$type
-    _po_helplines[$option]=$helpline
-    _po_excludes[$option]=$excludes
+    _po_params[$option.tag]=$tag
+    _po_params[$option.frequency]=$frequency
+    _po_params[$option.type]=$type
+    _po_params[$option.help]=$helpline
+    _po_params[$option.aliases]=$aliases
+    _po_params[$option.excludes]=$excludes
 
-    # If its an option then store its aliases in _po_aliases, else store
-    # the option name in _po_arguments. Thus this is how they can be
-    # distinguished from each other (in addition to checking for '-')
+    # Store option/argument name in appropriate array
     if [[ $option == -* ]]
     then
-      _po_aliases[$option]=$aliases
+      _po_options[$option]=1
     else
       _po_arguments=($_po_arguments $option)
     fi
+
+    # Store the special parameters
+    local parameter="" value=""
+    for parameter in "$parameters[@]"
+    do
+      if [[ $parameter == *=* ]]
+      then
+	value=${parameter#*=}
+	parameter=${parameter%%\=*}
+      else
+	value=1
+      fi
+      _po_params[$option.$parameter]=$value
+    done
+
   done
 
   return 0
@@ -243,22 +315,36 @@ _parse_opts_parseoption() {
 # This function handles the parsing of type definitions for
 # _parse_opts_parsehelp (uses locals directly)
 _parse_opts_parsetype() {
+
+  # Extract the special parameters if there are any
+  local -a parameters
+  if (( paraminfo[(I)\*] ))
+  then
+    parameters=($paraminfo[paraminfo[(I)\*]+1,-1])
+    paraminfo=($paraminfo[1,paraminfo[(I)\*]-1])
+  fi
+
   local type="$paraminfo[1]" basetype="$paraminfo[2]"
   local description="${(Q)paraminfo[3]}" action="${(Q)paraminfo[4]}"
 
-  # Report info on type if debugging enabled
-  if (( _po_debug ))
-  then
-    echo "type = '$type' {"
-    echo "  basetype    = '$basetype'"
-    echo "  description = '$description'"
-    echo "  action      = '$action'"
-    echo "}"
-  fi
+  # Store the main data for this type
+  _po_types[$type.base]=$basetype
+  _po_types[$type.complete.description]=$description
+  _po_types[$type.complete.action]=$action
 
-  _po_types_base[$type]=$basetype
-  _po_types_description[$type]=$description
-  _po_types_action[$type]=$action
+  # Store the special parameters
+  local parameter="" value=""
+  for parameter in "$parameters[@]"
+  do
+    if [[ $parameter == *=* ]]
+    then
+      value=${parameter#*=}
+      parameter=${parameter%%\=*}
+    else
+      value=1
+    fi
+    _po_types[$type.$parameter]=$value
+  done
 
   return 0
 }
@@ -270,9 +356,9 @@ _parse_opts_parsehelp() {
 
   # Process each line in the helptext. Note double newline (ie. empty line) is
   # converted to have a space so it doesn't get lost in the splitting
-  local line helpline
+  local line="" helpline=""
   local -a paraminfo
-  for line in ${(@f)argv[1]//$'\n\n'/$'\n \n'}
+  for line in ${(@f)${argv[1]//$'\\\n'}//$'\n\n'/$'\n \n'}
   do
 
     # If it starts with a '#' then its some kind of command line
@@ -463,17 +549,18 @@ _parse_opts_generatecompletiontype() {
   local _po_option="$argv[1]"
 
   # Extract the type without any leading '?'
-  local _po_type="${_po_types[$_po_option]#? }"
+  local _po_type="${_po_params[$_po_option.type]#? }"
 
   # Recursively convert user defined type into base type
-  while (( $+_po_types_base[$_po_type] ))
+  while (( $+_po_types[$_po_type.base] ))
   do
 
     # Take any settings supplied from the user defined type which we haven't already got
-    [[ -z $_po_description ]] && _po_description=$_po_types_description[$_po_type]
-    [[ -z $_po_action ]] && _po_action=$_po_types_action[$_po_type]    
+    [[ -z $_po_description ]] && _po_description=$_po_types[$_po_type.complete.description]
+    [[ -z $_po_action ]] && _po_action=$_po_types[$_po_type.complete.action]
+    [[ -z $_po_restrict ]] && _po_restrict=$_po_types[$_po_type.complete.restrict]
 
-    _po_type=$_po_types_base[$_po_type]
+    _po_type=$_po_types[$_po_type.base]
   done
 
   # Decode built in type to set anything not done already
@@ -502,10 +589,10 @@ _parse_opts_generatecompletiontype() {
       	  _po_values=(${(q)_po_values})
       	  _po_action="($_po_values)"
       	else
-  
+
       	  _po_hash=("${(@qkv)_po_hash}")
       	  _po_action="(("
-      	  local _po_key
+      	  local _po_key=""
       	  for _po_key in ${(k)_po_hash}
       	  do
       	    _po_action="$_po_action$_po_key\:$_po_hash[$_po_key] "
@@ -549,90 +636,111 @@ _parse_opts_generatecompletion() {
   local -a _po_specs
 
   # Process each option to build a list of specifications for _arguments.
-  # Careful to skip our magic --zsh-completion option
-  local _po_option
-  for _po_option in ${${(k)_po_aliases}:#--zsh-completion} $_po_arguments
+  local _po_option=""
+  for _po_option in ${(k)_po_options} $_po_arguments
   do
-    local _po_frequency="$_po_frequencies[$_po_option]"
-    integer _po_min_frequency=0 _po_max_frequency=0
-    _parse_opts_minmaxfrequency _po_min_frequency _po_max_frequency $_po_frequency || return
-
-    # Try to determine a description/completer from the type of this option
-    local _po_description="" _po_action=""
-    _parse_opts_generatecompletiontype $_po_option || return
-
-    local _po_spec=""
-    if [[ $_po_option == -* ]]
+    if (( ! _po_params[$_po_option.complete.hidden] ))
     then
+      local _po_frequency="$_po_params[$_po_option.frequency]"
+      integer _po_min_frequency=0 _po_max_frequency=0
+      _parse_opts_minmaxfrequency _po_min_frequency _po_max_frequency $_po_frequency || return
 
-      # Generate excludes clause if we have any
-      if [[ -n $_po_excludes[$_po_option] ]]
+      # Try to determine a description/completer from the type of this option
+      local _po_description="" _po_action="" _po_restrict=""
+      _parse_opts_generatecompletiontype $_po_option || return
+
+      # Default restriction of none
+      if [[ -z $_po_restrict ]]
       then
-        _po_spec="$_po_spec($_po_excludes[$_po_option])"
+        _po_restrict="none"
       fi
 
-      # Add repeating option flag if max frequency is not 1
-      if (( _po_max_frequency != 1 ))
+      local _po_spec=""
+      if [[ $_po_option == -* ]]
       then
-        _po_spec="$_po_spec*"
-      fi
 
-      # Add the main option name section
-      _po_spec="$_po_spec$_po_option"
+      	# Generate excludes clause if we have any
+      	if [[ -n $_po_params[$_po_option.excludes] ]]
+      	then
+      	  _po_spec="$_po_spec($_po_params[$_po_option.excludes])"
+      	fi
 
-      # If we have a long option which takes a parameter then add the '=' flag
-      # to say --option=value is valid
-      if [[ $_po_option == --* && -n $_po_action ]]
-      then
-        _po_spec="$_po_spec="
-      fi
+      	# Add repeating option flag if max frequency is not 1
+      	if (( _po_max_frequency != 1 ))
+      	then
+      	  _po_spec="$_po_spec*"
+      	fi
 
-      # Add the description of the option if one was successfully extracted from the help text
-      if [[ -n $_po_helplines[$_po_option] ]]
-      then
-        _po_spec="${_po_spec}[${_po_helplines[$_po_option]%%. *}]"
-      fi
+      	# Add the main option name section
+      	_po_spec="$_po_spec$_po_option"
 
-      # Now add the description and completer for the parameter, if we have one
-      if [[ -n $_po_action ]]
-      then
-        _po_spec="$_po_spec:$_po_description:$_po_action"
-      fi
+      	# If we have a long option which takes a parameter then add the '=' flag
+      	# to say --option=value is valid
+      	if [[ $_po_option == --* && -n $_po_action ]]
+      	then
+      	  _po_spec="$_po_spec="
+      	fi
 
-      # Collect the specifications
-      _po_specs=($_po_specs "'$_po_spec'")
+      	# Add the description of the option if one was successfully extracted from the help text
+      	if [[ -n $_po_params[$_po_option.help] ]]
+      	then
+      	  _po_spec="${_po_spec}[${_po_params[$_po_option.help]%%. *}]"
+      	fi
 
-    else
+      	# Now add the description and completer for the parameter, if we have one
+      	if [[ -n $_po_action ]]
+      	then
+      	  _po_spec="$_po_spec:$_po_description:$_po_action"
+      	fi
 
-      _po_spec="$_po_spec:$_po_description"
+      	# Collect the specifications
+      	_po_specs=($_po_specs "'$_po_spec'")
 
-      # Add the description of the argument if one was successfully extracted from the help text
-      if [[ -n $_po_helplines[$_po_option] ]]
-      then
-        _po_spec="$_po_spec - ${${_po_helplines[$_po_option]%%. *}//:/\\:}"
-      fi
-
-      _po_spec="$_po_spec:$_po_action"
-
-      # Collect the specifications
-      if (( _po_min_frequency >= 0 ))
-      then
-        repeat $_po_min_frequency
-        do
-          _po_specs=($_po_specs "'$_po_spec'")
-        done
-
-        if (( _po_max_frequency >= _po_min_frequency ))
-        then
-          repeat $(( _po_max_frequency - _po_min_frequency ))
-          do
-            _po_specs=($_po_specs "':$_po_spec'")
-          done
-	else
-          _po_specs=($_po_specs "'*$_po_spec'")
-	fi
       else
-        _po_specs=($_po_specs "'*$_po_spec'")
+
+      	_po_spec="$_po_spec:$_po_description"
+
+      	# Add the description of the argument if one was successfully extracted from the help text
+      	if [[ -n $_po_params[$_po_option.help] ]]
+      	then
+      	  _po_spec="$_po_spec - ${${_po_params[$_po_option.help]%%. *}//:/\\:}"
+      	fi
+
+      	_po_spec="$_po_spec:$_po_action"
+
+      	# Collect the specifications
+      	if (( _po_min_frequency >= 0 )) && [[ $_po_restrict == none ]]
+      	then
+      	  repeat $_po_min_frequency
+      	  do
+      	    _po_specs=($_po_specs "'$_po_spec'")
+      	  done
+
+      	  if (( _po_max_frequency >= _po_min_frequency ))
+      	  then
+      	    repeat $(( _po_max_frequency - _po_min_frequency ))
+      	    do
+      	      _po_specs=($_po_specs "':$_po_spec'")
+      	    done
+	  else
+      	    _po_specs=($_po_specs "'*$_po_spec'")
+	  fi
+      	else
+
+	  # Handle options to restrict 'words' array for completion action
+	  case $_po_restrict in
+	    match)
+      	      _po_specs=($_po_specs "'*::$_po_spec'")
+	      ;;
+	    normal)
+      	      _po_specs=($_po_specs "'*:$_po_spec'")
+	      ;;
+
+	    *) # none
+      	      _po_specs=($_po_specs "'*$_po_spec'")
+	      ;;
+	  esac
+      	fi
       fi
     fi
   done
@@ -656,7 +764,7 @@ _parse_opts_store() {
 
   # If tag is of the form [var] then instead assign to real variable.
   # Note possibility of clashes with our local variables here
-  local _po_tag="$_po_tags[$_po_name]"
+  local _po_tag="$_po_params[$_po_name.tag]"
 
   integer append=0
   if [[ $_po_tag == +* ]]
@@ -692,7 +800,7 @@ _parse_opts_store() {
 
         association*)
           # An associative array. Add option/value pair
-          local _po_oldvalue
+          local _po_oldvalue=""
           eval _po_oldvalue="\$${_po_tag}[$_po_name]"
           if (( append && $#_po_oldvalue ))
           then
@@ -756,18 +864,18 @@ _parse_opts_handletype() {
 
   # Check for leading '?' to disable validation
   integer _po_validate=1
-  if [[ $_po_types[$_po_name] == ?\ * ]]
+  if [[ $_po_params[$_po_name.type] == ?\ * ]]
   then
     _po_validate=0
   fi
 
   # Extract the type without any leading '?'
-  local _po_type="${_po_types[$_po_name]#? }"
+  local _po_type="${_po_params[$_po_name.type]#? }"
 
   # Recursively convert user defined type into base type
-  while (( $+_po_types_base[$_po_type] ))
+  while (( $+_po_types[$_po_type.base] ))
   do
-    _po_type=$_po_types_base[$_po_type]
+    _po_type=$_po_types[$_po_type.base]
   done
 
   local _po_param="${(Q)_po_type#*=}" _po_value
@@ -861,7 +969,7 @@ _parse_opts_dooptions() {
       --*) # Long argument
 
         # Check to see if the option exists
-        if (( $+_po_aliases[${_po_option%%\=*}] ))
+        if (( $+_po_options[${_po_option%%\=*}] ))
         then
 
           # Check to see if value was in option, ie. --name=value
@@ -894,7 +1002,7 @@ _parse_opts_dooptions() {
           _po_optiongroup=${_po_optiongroup#?}
 
           # Check to see if is a valid short option
-          if (( $+_po_aliases[-$_po_optionletter] ))
+          if (( $+_po_options[-$_po_optionletter] ))
           then
 
             # It is so process it as the type determines
@@ -935,10 +1043,10 @@ _parse_opts_doarguments() {
   fi
 
   # Process each argument specification
-  local _po_argument
+  local _po_argument=""
   for _po_argument in $_po_arguments
   do
-    local _po_frequency="$_po_frequencies[$_po_argument]"
+    local _po_frequency="$_po_params[$_po_argument.frequency]"
 
     # Ensure number of args to use is within required range
     integer _po_min=0 _po_max=0
@@ -987,14 +1095,13 @@ _parse_opts_doarguments() {
 # NB. Locals in this function must begin _po_
 _parse_opts_process() {
   local -a _po_arguments
-  local -A _po_tags _po_frequencies _po_types _po_aliases _po_excludes _po_helplines
-  local -A _po_types_base _po_types_description _po_types_action
-  local _po_helptext
+  local -A _po_options _po_params _po_types
+  local _po_helptext=""
   integer _po_minargs=0
 
   # Check for arguments. If we have one and it is not '-' then it is the help
   # string. Otherwise need to to get that from stdin
-  local _po_config
+  local _po_config=""
   if [[ -n $argv[1] && $argv[1] != - ]]
   then
     _po_config=$argv[1]
@@ -1011,24 +1118,20 @@ _parse_opts_process() {
   # Useful for debugging
   if (( _po_debug ))
   then
-    echo "_po_tags=(${(qqkv)_po_tags[@]})"
-    echo "_po_frequencies=(${(qqkv)_po_frequencies[@]})"
-    echo "_po_types=(${(qqkv)_po_types[@]})"
-    echo "_po_aliases=(${(qqkv)_po_aliases[@]})"
-    echo "_po_excludes=(${(qqkv)_po_excludes[@]})"
-    echo "_po_helplines=(${(qqkv)_po_helplines[@]})"
+    _parse_opts_showdata _po_params
+    echo
+    _parse_opts_showdata _po_types
+    echo
+    echo "_po_options=(${(ok)_po_options})"
     echo "_po_arguments=($_po_arguments)"
     echo "_po_minargs=$_po_minargs"
-    echo "_po_types_base=(${(qqkv)_po_types_base[@]})"
-    echo "_po_types_description=(${(qqkv)_po_types_description[@]})"
-    echo "_po_types_action=(${(qqkv)_po_types_action[@]})"
   fi
 
   # Perform the option recognition
   if _parse_opts_dooptions
   then
 
-    # If success and help was requested then give it. Note that it is up to
+    # If success, and help was requested then give it. Note that it is up to
     # the user to supply the help option before we can use it
     if (( _po_results[help] ))
     then
@@ -1088,7 +1191,7 @@ parse_opts() {
   setopt extended_glob
 
   # Extract arguments passed to us
-  local _po_ext_results _po_ext_argv _po_config
+  local _po_ext_results="" _po_ext_argv="" _po_config=""
   [[ $argv[1] != -- ]] && _po_config=$argv[1] && shift
   [[ $argv[1] != -- ]] && _po_ext_results=$argv[1] && shift
   [[ $argv[1] != -- ]] && _po_ext_argv=$argv[1] && shift
